/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Dekompress.java
 *
 * Created on 03 Jan 13, 12:19:15
 */
package sismul.Frame;

import java.awt.*;
import java.awt.event.ActionListener;
import java.io.File;
import javax.swing.DefaultListModel;
import javax.swing.JButton;
import javax.swing.JTextField;
import javax.swing.JList;
import sismul.proses.simpanfile;
import sismul.proses.pilihfile;
import sismul.proses.hapusfile;
import sismul.proses.kompress;
import sismul.Frame.menuutama;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.util.List;
import java.util.zip.ZipEntry;
import java.util.zip.ZipInputStream;
import sismul.proses.pilihdekompress;
import sismul.proses.prosesdekompress;
import sismul.proses.simpanfiledekompresi;

/**
 *
 * @author Cumi
 */
public class Dekompress extends javax.swing.JFrame {

 List<String> fileList;
  
    private File simpanfileya;
    private DefaultListModel list;
    public int b;
    
    /** Creates new form Dekompress */
    public Dekompress() {
        initComponents();
   
        
        list = new DefaultListModel();
        Listfile.setModel(list);
        NamaFolder.addActionListener(new simpanfiledekompresi(this));
        btnmasukandata.addActionListener(new pilihdekompress(this));   
      btndekompress.addActionListener(new prosesdekompress(this));
    
    
    }
    public JButton simpanfile(){
    
    return NamaFolder;
    }
    
    
    public void setFileSaveTo(File file) {
       this.simpanfileya = file;
	if (file == null) {
	    txtdata.setText("eweuhan");
	} else {
	    txtdata.setText(simpanfileya.getPath());
	}
        
    }
        public File buatdapatkanfile() {
       return simpanfileya;
    }
     public DefaultListModel getListModel() {
       return list;
    }
     public JButton Dekompress(){
     return btndekompress;
     }

       public JButton masukandata(){
    return btnmasukandata;
    
    }
    public JList dapatkanfilelist() {
        return Listfile;
    }
    
     

  
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnmasukandata = new javax.swing.JButton();
        btndekompress = new javax.swing.JButton();
        btnkembali1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Listfile = new javax.swing.JList();
        txtdata = new javax.swing.JTextField();
        NamaFolder = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnmasukandata.setText("Pilih File");
        btnmasukandata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmasukandataActionPerformed(evt);
            }
        });

        btndekompress.setText("DEKOMPRESS");
        btndekompress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndekompressActionPerformed(evt);
            }
        });

        btnkembali1.setText("Kembali");

        Listfile.setEnabled(false);
        jScrollPane1.setViewportView(Listfile);

        NamaFolder.setText("Nama Folder");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnmasukandata, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnkembali1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NamaFolder))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(74, 74, 74)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 162, Short.MAX_VALUE)
                                        .addComponent(btndekompress, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(15, 15, 15))
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 339, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtdata, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)))))
                .addGap(27, 27, 27))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NamaFolder, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtdata, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(btnmasukandata, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btndekompress, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnkembali1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnmasukandataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmasukandataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnmasukandataActionPerformed

    private void btndekompressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndekompressActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_btndekompressActionPerformed

    /**
     * @param args the command line arguments
     */
    
 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList Listfile;
    private javax.swing.JButton NamaFolder;
    private javax.swing.JButton btndekompress;
    private javax.swing.JButton btnkembali1;
    private javax.swing.JButton btnmasukandata;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtdata;
    // End of variables declaration//GEN-END:variables

    public void unZipIt(String INPUT_ZIP_FILE, String OUTPUT_FOLDER) {
     INPUT_ZIP_FILE="C:\\aa.zip";
      OUTPUT_FOLDER="C:\\out" ;
     
        
        
        byte[] buffer = new byte[1024];
 
     try{
 
    	//create output directory is not exists
    	File folder = new File(OUTPUT_FOLDER);
    	if(!folder.exists()){
    		folder.mkdir();
    	}
 
    	//get the zip file content
    	ZipInputStream zis = 
    		new ZipInputStream(new FileInputStream(INPUT_ZIP_FILE));
    	//get the zipped file list entry
    	ZipEntry ze = zis.getNextEntry();
 
    	while(ze!=null){
 
    	   String fileName = ze.getName();
           File newFile = new File(OUTPUT_FOLDER + File.separator + fileName);
 
           System.out.println("file unzip : "+ newFile.getAbsoluteFile());
 
            //create all non exists folders
            //else you will hit FileNotFoundException for compressed folder
            new File(newFile.getParent()).mkdirs();
 
            FileOutputStream fos = new FileOutputStream(newFile);             
 
            int len;
            while ((len = zis.read(buffer)) > 0) {
       		fos.write(buffer, 0, len);
            }
 
            fos.close();   
            ze = zis.getNextEntry();
    	}
 
        zis.closeEntry();
    	zis.close();
 
    	System.out.println("Done");
 
    }catch(IOException ex){
       ex.printStackTrace(); 
    }
   } 
    }



